### ISSUE TITLE
support --access-token-path so that tokens are not in cleartext

### ISSUE THREAD

**Issue by earl-warren** [the-draupnir-project/helm-charts#1]
As it currently stands, the token must be provided in the config file in cleartext

https://github.com/the-draupnir-project/helm-charts/blob/57a29f5e61be20a73e69878d13d79a96c0611a9a/charts/draupnir/values.yaml#L119

it would be better to support --access-token-path instead so that it can be obtained from a file mounted from a k8s secrets instead.

https://the-draupnir-project.github.io/draupnir-documentation/bot/starting_draupnir#secret-management

## Workaround for flux

When using flux, [there is a convenient workaround](https://github.com/the-draupnir-project/helm-charts/issues/1#issuecomment-2900832215) for which [an example is available](https://codeberg.org/forgejo/k8s-cluster/src/commit/cac7200ba348d46b88b95a2cf7ef45ef268c24c4/flux/apps/moderation) which is deployed in the [Forgejo chatrooms](https://matrix.to/#/#forgejo:matrix.org).

**Comment by MTRNord** [comment]
Oops yeah. There is also a but more work to do to finish this up :) i just got side tracked. But thabk you for mentioning so i wont forget!

**Comment by earl-warren** [comment]
I'm willing to propose a pull request to fix this. Unless it is too early stages for such a contribution. Maybe you're actively working on it at the moment.

Please let me know: I can set aside time tomorrow to work on that.

**Comment by MTRNord** [comment]
I am trying to get around to it on the weekend but no hard promises, so I take the PR if you want to :)

The only thing I am currently still working on is an appservice ready variant of the chart, but that shouldn't conflict :) 

Just a warning that while I technically use the CI already elsewhere it might fail since I didnt test it in this repo. So in case it does dont worry :)

**Comment by earl-warren** [comment]
Great to know, I'll work on it tomorrow. 

FYI the goal is to use this chart as part of the https://forgejo.org/ infrastructure which is at https://codeberg.org/forgejo/k8s-cluster/. The alternative would be to create a local chart similar to a few others https://codeberg.org/forgejo/k8s-cluster/src/branch/main/flux/apps/charts

But contributing to your early effort seems to be a better choice than accumulating technical debt.

**Comment by earl-warren** [comment]
I started implementing the needful but I think there actually is a simpler way to do the same, only it needs to be documented (I forgot about that possibility) . Assuming a secret is created as follows:

```
apiVersion: v1
kind: Secret
metadata:
  name: draupnir-token
type: Opaque
stringData:
  values.yaml: |
    config:
       accessToken: "YOUR_TOKEN_HERE"
```

It can then be used with `valuesFrom`

```
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drap
spec:
 ...
  # https://fluxcd.io/flux/components/helm/helmreleases/#values-references
  valuesFrom:
    - kind: Secret
      name: draupnir-token
  values:
   ...
```

and it will be merged into one config file.

The [arguments are needed](https://the-draupnir-project.github.io/draupnir-documentation/bot/starting_draupnir) when invoking draupnir with a static config file. In the context of flux, the config file is composed dynamically and there is no need for such arguments.
